CREATE DATABASE Pardalis;

USE Pardalis;

CREATE TABLE USUARIO(
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
USUARIO_EMAIL VARCHAR(40) NOT NULL,
USUARIO_SENHA VARCHAR(40) NOT NULL
)AUTO_INCREMENT = 022200;