CREATE DATABASE Pardalis;

USE Pardalis;

CREATE TABLE EMPRESA(
    EMPRESA_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPRESA_NOME VARCHAR(60),
    EMPRESA_CNPJ CHAR(14),
    EMPRESA_GERENTE VARCHAR(60),
    EMPRESA_EMAIL VARCHAR(60),
    EMPRESA_SENHA CHAR(32)
);

CREATE TABLE USUARIO(
    USUARIO_ID INT' PRIMARY KEY AUTO_INCREMENT,
    USUARIO_EMAIL VARCHAR(110) NOT NULL,
    USUARIO_SENHA 'VARCHAR(110) NOT NULL
)AUTO_INCREMENT = 022200;

INSERT INTO Usuario VALUES (null, "ivan.miranda@sptech.school", "sptech");

SELECT * FROM USUARIO;