CREATE DATABASE PARDALIS;
USE PARDALIS;

CREATE TABLE Usuario(
	ID_usuario INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_NOME VARCHAR(60) NOT NULL,
    USUARIO_EMAIL VARCHAR(60) NOT NULL CHECK(USUARIO_EMAIL = '%@%'),
    USUARIO_SENHA CHAR(128) NOT NULL
);

CREATE TABLE MAQUINA(
	ID_MAQUINA INT PRIMARY KEY AUTO_INCREMENT,
    MAQUINA_NOME VARCHAR(50),
    MAQUINA_SISTEMA_OPERACIONAL VARCHAR(50),
    MAQUINA_MODELO_PROCESSADOR VARCHAR(50),
    MAQUINA_QTD_CPU_FISICA INT,
    MAQUINA_QTD_CPU_VIRTUAL INT,
    MAQUINA_QTD_RAM INT,
    MAQUINA_ARMAZENAMENTO_MAXIMO INT
);

CREATE TABLE REGISTRO(
	ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    REGISTRO_MOMENTO DATETIME NOT NULL,
    REGISTRO_TEMP_CPU DECIMAL(5, 2),
    REGISTRO_PORC_CPU DECIMAL(5, 2),
    REGISTRO_PORC_RAM DECIMAL(5, 2),
    REGISTRO_PORC_DISCO DECIMAL(5, 2),
    REGISTRO_NIVEL_CACHE_CPU DECIMAL(5, 2),
    REGISTRO_FK_MAQUINA INT,
    FOREIGN KEY (REGISTRO_FK_MAQUINA) REFERENCES MAQUINA(ID_MAQUINA)
);