CREATE DATABASE Pardalis;

USE Pardalis;

CREATE TABLE USUARIO(
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
USUARIO_EMAIL VARCHAR(110) NOT NULL,
USUARIO_SENHA VARCHAR(110) NOT NULL
)AUTO_INCREMENT = 022200;

INSERT INTO Usuario VALUES (null, "ivan.miranda@sptech.school", "sptech");

SELECT * FROM USUARIO;